name: Excuter/omp-simd Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]
        backend: [ompsimd]
        exclude:
          - os: linux-latest
            
          - os: macos-latest
            backend: cuda
          - os: windows-latest
            backend: cuda
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    # 公共依赖安装
    - name: Install Dependencies
      run: |
        sudo apt-get install -y build-essential cmake  libopenblas-dev libyaml-cpp-dev  libjemalloc-dev clang git
    # 构建执行器
    - name: CMake Build
      run: |
        mkdir build && cd build
        cmake ..
        make -j4
